---

- name: Install Java 1.7 and some basic dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip
    - openjdk-8-jdk
    - python-selinux
    - python-semanage

- name: Download JBoss from jboss.org
  get_url:
    url: https://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  unarchive:
    dest: /usr/share
    src: /opt/jboss-as-7.1.1.Final.zip
    creates: /usr/share/jboss-as
    copy: no

- name: Rename install directory
  template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  group:
    name: jboss

- name: Add user "jboss"
  user:
    name: jboss
    group: jboss
    home: /usr/share/jboss-as

