---

- name: Install Java 1.8 and some basic dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - unzip
    - default-jdk 

- name: Download JBoss from jboss.org
  get_url:
    url: https://download.jboss.org/wildfly/22.0.1.Final/wildfly-22.0.1.Final.zip
    dest: /opt/wildfly-22.0.1.Final.zip

- name: Extract archive
  unarchive:
    dest: /opt/
    src: /opt/wildfly-22.0.1.Final.zip
    copy: no



- name: Rename install directory
  template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss

- name: Add group "jboss"
  group:
    name: jboss

- name: Add user "jboss"
  user:
    name: jboss
    group: jboss
    home: /opt/jboss

