---

- name: Install ntp
  package:
    name: ntp
    state: present
  tags: ntp

- name: Install common dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - libsemanage1
    - libselinux1
    - firewalld

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: yes
  tags: ntp
