---

- name: Install httpd and php
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2 
    - php
    - php-mysql

- name: Install web role specific dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - git

- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Insert firewalld rule for httpd
  firewalld: port={{ httpd_port }}/tcp permanent=true state=enabled immediate=yes

- name: apache2 service state
  service:
    name: apache2 
    state: started
    enabled: yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name: httpd_can_network_connect_db
    state: true
    persistent: yes
